Update patch set 2
Patch Set 2: Verified-1

Default value annotation for String column seems not to be honored during insert statement:

 SQLException: NULL not allowed for column "STRING_DEFAULT"

If String column is commented out, then all wrapper types columns are failing to be read with missing default constructor error, i. e.:

 java.lang.NoSuchMethodError: java.lang.Boolean: method <init>()V not found
	at com.google.gwtorm.data.Person_Access_people_GwtOrm$$1.bindOneFetch(Unknown Source)
	at com.google.gwtorm.jdbc.JdbcAccess.queryOne(JdbcAccess.java:113)
	at com.google.gwtorm.data.Person_Access_people_GwtOrm$$1.get(Unknown Source)

If wrapper classes are not supported by gwtorm yet, then the default value annotations, added in the original change, make no sense and should be removed (for Boolean, Character, Integer, Long and Short). Or alternatively gwtorm should fully support wrapper classes.

Patch-set: 2
Reviewer: Gerrit User 1011323 <1011323@173816e5-2b9a-37c3-8a2e-48639d4f1153>
Label: Verified=-1